[package]
org = "sanduni"
name = "Weather_assistant"
version = "0.1.0"
distribution = "2201.9.3"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "openai.assistants"
version = "1.0.0"
repository = "local"