[package]
distribution = "2201.9.2"
org = "ballerinax"
name = "openai.assistants"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = []
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-openai.assistants"

[build-options]
observabilityIncluded = true